name: DMP.md to DMP.pdf and DMP.html
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  export-dmp:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: export
      - uses: actions/upload-artifact@v4
        with:
          name: export
          path: export
