name: DMP.md to DMP.pdf and DMP.html
# This workflow is triggered on pushes to the repository.
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  export-dmp:
    name: Build PDF and HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            README.md
            README.html
