name: DMP.md to DMP.pdf and DMP.html
# This workflow is triggered on pushes to the repository.
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  export-dmp:
    name: Build PDF and HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: out
      - name: Rename output files
        run: |
            cp out/README.pdf ${{ runner.temp }}/QMC-DMP.pdf 
            cp out/README.html ${{ runner.temp }}/QMC-DMP.html 
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ runner.temp }}/QMC-DMP.pdf
            ${{ runner.temp }}/QMC-DMP.html
